### ISSUE TITLE
Quando mudar de casa incluir automaticamente os dados da proposição na nova casa

### ISSUE THREAD

**Issue by andresmrm** [analytics-ufcg/agora-digital#225]
Atualmente temos que colocar o id_ext de cada casa na mão. Mas isso é ruim porque, conforme o tempo passa, as proposições mudam de casa e nós deixamos de acompanha-lhas.

A questão é: como achar na página de uma casa, o link para a proposição na próxima casa?

Ex.: Essa foi da Câmara para o Senado. Na segunda tem link para a primeira, mas não o contrário.
http://www.camara.gov.br/proposicoesWeb/fichadetramitacao?idProposicao=1635730
https://www25.senado.leg.br/web/atividade/materias/-/materia/126084

**Comment by thayannevls** [comment]
Solução que vi é identificar quando na tramitação possui o texto *"Remessa ao Senado Federal"*, e fazer uma pesquisa com o número da PL no site do senado. Bem, direto no site funciona a [pesquisa](http://www6g.senado.leg.br/busca/?portal=Atividade+Legislativa&q=PL+2646%2F2015++), tentei usar a endpoint [/materia/pesquisa/lista](http://legis.senado.leg.br/dadosabertos/docs/ui/index.html#!/PesquisaMateriaService/resource_PesquisaMateriaService_materiaListaPesquisa_GET) para poder fazer a pesquisa sem precisar ser no site, mas ainda não entendi muito os parâmetros.

O mesmo seria feito na câmara

**Comment by andresmrm** [comment]
Tinha pensando em usar essa pesquisa também. Não é o ideal, mas não estou vendo outra forma...
